## Write a Numpy program to compute the multiplication of two given matrixes

In [9]:
import numpy as np

In [10]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
arr_1d=np.array(([1,2,3],[5,7,9],[9,8,7]))
arr_1d

array([[1, 2, 3],
       [5, 7, 9],
       [9, 8, 7]])

In [12]:
arr_1d*arr_2d

array([[  5,  20,  45],
       [100, 175, 270],
       [315, 320, 315]])

## Write a NumPy program to compute the determinant of a given square array

In [14]:
np.sqrt(arr_1d)

array([[1.        , 1.41421356, 1.73205081],
       [2.23606798, 2.64575131, 3.        ],
       [3.        , 2.82842712, 2.64575131]])

In [20]:
#another solution

In [21]:
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0], [1, 2]])
print("Original 2-d array")
print(a)
print("Determinant of the said 2-D array:")
print(np.linalg.det(a))


Original 2-d array
[[1 0]
 [1 2]]
Determinant of the said 2-D array:
2.0


## Write a NumPy program to compute the cross product of two given vectors

In [15]:
arr3=np.arange(0,9)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
arr4=np.arange(0,9)
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
arr3*arr4

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64])

In [22]:
#anather solution

In [23]:
import numpy as np
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.cross(p, q)
result2 = np.cross(q, p)
print("cross product of the said two vectors(p, q):")
print(result1)
print("cross product of the said two vectors(q, p):")
print(result2)

original matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
cross product of the said two vectors(p, q):
[ 2 -3]
cross product of the said two vectors(q, p):
[-2  3]


## Write a NumPy program to compute the condition number of a given matrix

In [18]:
import numpy as np
from numpy import linalg as LA
a = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]])
print("Original matrix:")
print(a)
print("The condition number of the said matrix:")
print(LA.cond(a))

Original matrix:
[[ 1  0 -1]
 [ 0  1  0]
 [ 1  0  1]]
The condition number of the said matrix:
1.4142135623730951


## Write a NumPy program to compute the inverse of a given matrix

In [19]:
import numpy as np
m = np.array([[1,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.inv(m)
print("Inverse of the said matrix:")
print(result)

Original matrix:
[[1 2]
 [3 4]]
Inverse of the said matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]
